### ISSUE TITLE
ImportError: cannot import name Client

### ISSUE THREAD

**Issue by sowinski** [mailjet/mailjet-apiv3-python#16]
Hi,

I've installed your package with:
pip install mailjet_rest

But if I try to import your Client i got this error:

> from mailjet_rest import Client

`>>> from mailjet_rest import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mailjet_rest/__init__.py", line 4, in <module>
    from .client import Client
  File "/usr/local/lib/python2.7/dist-packages/mailjet_rest/client.py", line 7, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/requests/utils.py", line 25, in <module>
    from . import certs
ImportError: cannot import name certs
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python2.7/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python2.7/dist-packages/apport/report.py", line 28, in <module>
    import problem_report
  File "/usr/lib/python2.7/dist-packages/problem_report.py", line 15, in <module>
    from email.encoders import encode_base64
  File "email.py", line 2, in <module>
    from mailjet_rest import Client
  File "/usr/local/lib/python2.7/dist-packages/mailjet_rest/__init__.py", line 4, in <module>
    from .client import Client
  File "/usr/local/lib/python2.7/dist-packages/mailjet_rest/client.py", line 7, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/requests/utils.py", line 25, in <module>
    from . import certs
ImportError: cannot import name certs

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mailjet_rest/__init__.py", line 4, in <module>
    from .client import Client
  File "/usr/local/lib/python2.7/dist-packages/mailjet_rest/client.py", line 7, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/requests/utils.py", line 25, in <module>
    from . import certs
ImportError: cannot import name certs
`
What is wrong?

**Comment by jordanambra** [comment]
It looks like you may have an old version of `requests`. Try upgrading?
