### ISSUE TITLE
Error in creating Twitter Bot

### ISSUE THREAD

**Issue by Hacksmith64** [mailjet/mailjet-apiv3-python#58]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Acer\Desktop\my_bot\venv\lib\site-packages\tweepy\binder.py", line 252, in _call
    return method.execute()
  File "C:\Users\Acer\Desktop\my_bot\venv\lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 32, 'message': 'Could not authenticate you.'}]

Help me to clear this issue. I am using python 3 in Windows 7 and I have run it in PyCharm?

**Comment by diskovod** [comment]
Problem is not related to Python wrapper. Closing
